### ISSUE TITLE
Helmet is not a function

### ISSUE THREAD

**Issue by laser-cake** [ljlm0402/typescript-express-starter#37]
When trying to run the application, an exception is being thrown:

`      this.app.use(helmet());
                         ^
TypeError: helmet_1.default is not a function
    at App.initializeMiddlewares (C:\Source\TnT\TnT2\src\app.ts:39:26)
    at new App (C:\Source\TnT\TnT2\src\app.ts:20:10)
    at Object.<anonymous> (C:\Source\TnT\TnT2\src\server.ts:10:13)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Module.m._compile (C:\Source\TnT\TnT2\node_modules\ts-node\src\index.ts:1043:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Source\TnT\TnT2\node_modules\ts-node\src\index.ts:1046:12)        
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)`

The fix seems to be changing the import statement in app.ts from:

`import helmet from 'helmet';`

to

`import * as helmet from 'helmet'`

I'm happy to submit to resolve this myself, but I'm not sure if this is by design or not.

**Comment by ljlm0402** [comment]
@laser-cake 

https://github.com/ljlm0402/typescript-express-starter/pull/33
Um... it's modified by pull request, but it's strange....
