### ISSUE TITLE
Cannot find module './'

### ISSUE THREAD

**Issue by AnkitKaura** [ljlm0402/typescript-express-starter#91]
### Summary(요약)

Getting error at npm start command

### Additional Details(추가적인 세부 사항)

1. Project setup using command   **npx typescript-express-starter "project name"**

2.  npm run start

**Following error generated**

`npx: installed 61 in 14.582s
Info: === tsc-alias starting ===
Info: 27 files were affected!
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module './'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\Paxcom\kinator-connector\dist\server.js:6:40)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kinator-connector@0.0.0 start: `npm run build && cross-env NODE_ENV=production node dist/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kinator-connector@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

**Comment by timothystewart6** [comment]
I am seeing the same thing.  It happens when you build the app or run the docker container which builds the app.

**Comment by ljlm0402** [comment]
@AnkitKaura 

Thank you for leaving the bug issue.
We will deal with the same issue together. #89
