### ISSUE TITLE
Sequelize template seems to be broken 

### ISSUE THREAD

**Issue by ajvarparadise** [ljlm0402/typescript-express-starter#97]
### Describe the Bug(버그 설명)

When using the sequelize template and running the project with `docker compose up -d` I get an error when the node application tries to interact with the database. 

Not sure if the templates are suppose to be working examples. 

### Version to Reproduce(현재 사용한 버전)

Used with Docker

### Steps to Reproduce(재현 순서)

1. npx typescript-express-starter 
2.  select `sequelize` template
3. GET request --> `http://localhost:3000/users`

### Actual Behavior(실제 동작)

```
error: [GET] /users >> StatusCode:: 500, Message:: connect ECONNREFUSED 127.0.0.1:3306
```

### Additional Context(추가 사항)

```
ConnectionRefusedError [SequelizeConnectionRefusedError]: connect ECONNREFUSED 127.0.0.1:3306

at ConnectionManager.connect (/app/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:116:17)

at processTicksAndRejections (internal/process/task_queues.js:93:5)

at ConnectionManager._connect (/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:318:24)

at /app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:250:32

at ConnectionManager.getConnection (/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:280:7)

at /app/node_modules/sequelize/lib/sequelize.js:613:26

at MySQLQueryInterface.select (/app/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)

at Function.findAll (/app/node_modules/sequelize/lib/model.js:1753:21)

at UserService.findAllUser (/app/src/services/users.service.ts:12:29)

at UsersController.getUsers (/app/src/controllers/users.controller.ts:11:40) {

parent: Error: connect ECONNREFUSED 127.0.0.1:3306

at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {

errno: -111,

code: 'ECONNREFUSED',

syscall: 'connect',

address: '127.0.0.1',

port: 3306,

fatal: true

},

original: Error: connect ECONNREFUSED 127.0.0.1:3306

at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {

errno: -111,

code: 'ECONNREFUSED',

syscall: 'connect',

address: '127.0.0.1',

port: 3306,

fatal: true

}

}

2021-06-09 19:19:44 error: connect ECONNREFUSED 127.0.0.1:3306
```

**Comment by ljlm0402** [comment]
@ajvarparadise 

Thank you for the issues and pull requests.
